export const SET_CURRENT_USER   = "SET_CURRENT_USER";
export const LOGOUT             = "LOGOUT";
export const REGISTER_SUCCESS   = 'REGISTER_SUCCESS';
export const PAY_COLLATERAL_SUCCESS = 'PAY_COLLATERAL_SUCCESS';
export const REPAY_LOAN_SUCCESS = 'REPAY_LOAN_SUCCESS';
export const REQUEST_LOAN_SUCCESS = 'REQUEST_LOAN_SUCCESS';
export const GET_ERRORS         = 'GET_ERRORS';
